import type { Match } from './page';

type Status = 'ALL' | 'SCHEDULED' | 'IN_PROGRESS' | 'FINISHED';
interface FilterProps { searchTerm: string; filterStatus: Status; filterTournament: string; onSearch: (value: string) => void; onStatus: (value: Status) => void; onTournament: (value: string) => void; }
export function LocateMatchesFilters({ searchTerm, filterStatus, filterTournament, onSearch, onStatus, onTournament }: FilterProps) {
  return <div className="bg-white rounded-xl shadow-sm border p-6 mb-6"><h2 className="text-lg font-semibold text-gray-900 mb-4">Filtros</h2><div className="grid grid-cols-1 md:grid-cols-3 gap-4"><div><label htmlFor="locate-search" className="block text-sm font-medium text-gray-700 mb-1">Buscar</label><input id="locate-search" type="text" value={searchTerm} onChange={(e) => onSearch(e.target.value)} placeholder="Jogador ou torneio..." className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-sky-500" /></div><div><label htmlFor="locate-status" className="block text-sm font-medium text-gray-700 mb-1">Status</label><select id="locate-status" value={filterStatus} onChange={(e) => onStatus(e.target.value as Status)} className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-sky-500"><option value="ALL">Todos</option><option value="SCHEDULED">Agendadas</option><option value="IN_PROGRESS">Em Andamento</option><option value="FINISHED">Finalizadas</option></select></div><div><label htmlFor="locate-tournament" className="block text-sm font-medium text-gray-700 mb-1">Torneio</label><select id="locate-tournament" value={filterTournament} onChange={(e) => onTournament(e.target.value)} className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-sky-500"><option value="">Todos</option><option value="Copa Clube 2026">Copa Clube 2026</option><option value="Torneio de Verão">Torneio de Verão</option><option value="Campeonato Interno">Campeonato Interno</option></select></div></div></div>;
}

function statusLabel(status: Match['state']) { return status === 'SCHEDULED' ? 'Agendada' : status === 'IN_PROGRESS' ? 'Em Andamento' : 'Finalizada'; }
function statusColor(status: Match['state']) { return status === 'SCHEDULED' ? 'bg-blue-100 text-blue-700' : status === 'IN_PROGRESS' ? 'bg-green-100 text-green-700' : 'bg-gray-100 text-gray-700'; }
function actionLabel(status: Match['state']) { return status === 'SCHEDULED' ? 'Anotar' : status === 'IN_PROGRESS' ? 'Ver Placar' : 'Relatório'; }
function actionColor(status: Match['state']) { return status === 'SCHEDULED' ? 'bg-sky-600 hover:bg-sky-700' : status === 'IN_PROGRESS' ? 'bg-green-600 hover:bg-green-700' : 'bg-gray-600 hover:bg-gray-700'; }

export function LocateMatchesResults({ matches, loading, onOpen }: { matches: Match[]; loading: boolean; onOpen: (match: Match) => void }) {
  return <div className="bg-white rounded-xl shadow-sm border"><div className="p-6 border-b flex items-center justify-between"><h2 className="text-lg font-semibold text-gray-900">Partidas Encontradas</h2><span className="text-sm text-gray-500">{matches.length} resultado(s)</span></div>{loading ? <EmptyState icon="⏳" title="Carregando..." text="Buscando partidas no banco de dados." /> : matches.length ? <div className="divide-y">{matches.map((match) => <MatchResult key={match.id} match={match} onOpen={onOpen} />)}</div> : <EmptyState icon="🔍" title="Nenhuma partida encontrada" text="Tente ajustar os filtros ou buscar por outros termos." />}</div>;
}
function MatchResult({ match, onOpen }: { match: Match; onOpen: (match: Match) => void }) { return <div className="p-4 hover:bg-gray-50 transition-colors flex items-center justify-between"><div className="flex-1"><div className="flex items-center gap-3 mb-2"><span className={`px-2 py-1 rounded text-xs font-medium ${statusColor(match.state)}`}>{statusLabel(match.state)}</span>{match.tournamentName && <span className="text-xs text-gray-500 bg-gray-100 px-2 py-1 rounded">{match.tournamentName}</span>}{match.round && <span className="text-xs text-gray-500 bg-gray-100 px-2 py-1 rounded">{match.round}</span>}</div><div className="flex items-center gap-2"><span className="font-semibold text-gray-900">{match.player1.name}</span><span className="text-gray-400">vs</span><span className="font-semibold text-gray-900">{match.player2.name}</span></div>{match.scheduledAt && <p className="text-sm text-gray-500 mt-1">{new Date(match.scheduledAt).toLocaleString('pt-BR', { day: '2-digit', month: '2-digit', year: 'numeric', hour: '2-digit', minute: '2-digit' })}</p>}</div><button onClick={() => onOpen(match)} className={`px-4 py-2 text-white text-sm font-medium rounded-lg transition-colors ${actionColor(match.state)}`}>{actionLabel(match.state)}</button></div>; }
function EmptyState({ icon, title, text }: { icon: string; title: string; text: string }) { return <div className="p-12 text-center"><div className="text-6xl mb-4">{icon}</div><h3 className="text-lg font-semibold text-gray-900 mb-2">{title}</h3><p className="text-gray-500">{text}</p></div>; }
