import { logger } from '@/lib/logger';
import { ScoringEngine } from '@/core/scoring/engine';
import type { ScoringState, HistoryEntry } from '@/core/scoring/types';
import type { SuspendedSessionState } from './useSessionManager';
import type { MatchData } from '@/hooks/useScoringHandlers';
import { normalizeMatchTiebreakState } from './useSessionManager.utils';
import { restoreFreshScoreState, syncOfflinePoints } from './useSuspendedSession.resume.helpers';

type EngineConfig = Parameters<typeof ScoringEngine.fromSerialized>[0];
export type ResumeConfig = { suspendedSession: SuspendedSessionState; match: MatchData; matchId: string; fetchMatch: (forceEngineReset?: boolean) => Promise<void>; sessionIdRef: React.MutableRefObject<string | null>; tokenRef: React.MutableRefObject<string | null>; engineRef: React.MutableRefObject<ReturnType<typeof ScoringEngine.fromSerialized> | null>; setScoreState: (state: ScoringState) => void; setSessionActive: (active: boolean) => void; setFloorCurrentSets: (sets: { player1: number; player2: number } | null) => void; startSession: (matchId: string, createNew: boolean) => Promise<{ id: string }>; };

function engineConfig(config: ResumeConfig): EngineConfig { return { format: config.match.format as EngineConfig['format'], player1Id: config.match.player1.id, player2Id: config.match.player2.id, initialServerId: config.match.initialServerId || config.match.player1.id }; }
async function start(config: ResumeConfig) { const session = await config.startSession(config.matchId, false); config.sessionIdRef.current = session.id; config.setSessionActive(true); return engineConfig(config); }
export async function resumeFromSnapshot(config: ResumeConfig) { const serialized = await start(config); const snapshot = config.suspendedSession.matchStateSnapshot; if (!snapshot) return; const parsed = JSON.parse(snapshot) as { history?: HistoryEntry[] }; const history = Array.isArray(parsed.history) ? parsed.history : []; await syncOfflinePoints(config.matchId, config.tokenRef.current, history.slice(config.suspendedSession.bankPointCount)); await restoreFreshScoreState(config.matchId, config.tokenRef.current, serialized, config.engineRef, config.setScoreState); }
export async function resumeFromBank(config: ResumeConfig) { const serialized = await start(config); const snapshot = config.suspendedSession.matchStateSnapshot; if (snapshot) { config.engineRef.current = ScoringEngine.fromSerialized(serialized, JSON.stringify(normalizeMatchTiebreakState(JSON.parse(snapshot), config.match.format))); applyCanonicalState(config); return; } if (config.suspendedSession.bankScoreState) { const normalized = normalizeMatchTiebreakState(config.suspendedSession.bankScoreState, config.match.format); config.engineRef.current = ScoringEngine.fromSerialized(serialized, JSON.stringify(normalized)); config.setScoreState(config.engineRef.current.getState() as ScoringState); } }
function applyCanonicalState(config: ResumeConfig) { const canonical = config.suspendedSession.bankScoreState ?? config.match.scoreState; if (canonical) { config.engineRef.current?.reconcileWithCanonicalState(canonical, config.suspendedSession.bankPointCount); config.setScoreState(canonical); return; } config.setScoreState(config.engineRef.current?.getState() as ScoringState); }
export function calculateFloorSets(config: ResumeConfig) { const state = config.engineRef.current?.getState() as ScoringState | null; const last = state?.sets?.[state.sets.length - 1]; if (last) return last.isTiebreak && last.tiebreakScore ? last.tiebreakScore : { player1: last.player1, player2: last.player2 }; const bank = config.suspendedSession.bankScoreState?.sets; const bankLast = bank?.[bank.length - 1]; return bankLast ? { player1: bankLast.player1, player2: bankLast.player2 } : null; }
export function logFloorFallback(value: { player1: number; player2: number } | null) { if (value) logger.log('[useSuspendedSession] Floor fallback from bank:', value); }
