import { useCallback } from 'react';
import type { MutableRefObject } from 'react';

const PREFERRED_MIME = 'audio/webm;codecs=opus';
const FALLBACK_MIME = 'audio/mp4';
const MAX_DURATION_MS = 15_000;
export type RecorderRefs = { mediaRecorderRef: MutableRefObject<MediaRecorder | null>; streamRef: MutableRefObject<MediaStream | null>; chunksRef: MutableRefObject<Blob[]>; timerRef: MutableRefObject<ReturnType<typeof setInterval> | null>; startTimeRef: MutableRefObject<number>; audioElementRef: MutableRefObject<HTMLAudioElement | null>; };
function getSupportedMime() { if (typeof MediaRecorder === 'undefined' || typeof MediaRecorder !== 'function') return null; if (MediaRecorder.isTypeSupported(PREFERRED_MIME)) return PREFERRED_MIME; if (MediaRecorder.isTypeSupported(FALLBACK_MIME)) return FALLBACK_MIME; return null; }

export function useVoiceRecorderOperations(refs: RecorderRefs, clear: () => void, stopPreview: () => void, cleanupStream: () => void, cleanupTimer: () => void, setError: (error: string | null) => void, setState: (state: 'idle' | 'recording' | 'recorded') => void, setAudioBlob: (blob: Blob | null) => void, setDurationMs: (duration: number) => void, audioBlob: Blob | null) {
  const { mediaRecorderRef, streamRef, chunksRef, timerRef, startTimeRef, audioElementRef } = refs;
  const startRecording = useCallback(async () => { clear(); setError(null); const mime = getSupportedMime(); if (!mime) { setError('Gravação de áudio não suportada neste navegador'); return; } try { const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); streamRef.current = stream; const recorder = new MediaRecorder(stream, { mimeType: mime }); mediaRecorderRef.current = recorder; chunksRef.current = []; recorder.ondataavailable = (event) => { if (event.data.size > 0) chunksRef.current.push(event.data); }; recorder.onstop = () => { const blob = new Blob(chunksRef.current, { type: mime }); const elapsed = Date.now() - startTimeRef.current; setAudioBlob(blob); setDurationMs(Math.min(elapsed, MAX_DURATION_MS)); setState('recorded'); cleanupTimer(); cleanupStream(); }; recorder.start(100); startTimeRef.current = Date.now(); setState('recording'); timerRef.current = setInterval(() => { const elapsed = Date.now() - startTimeRef.current; setDurationMs(elapsed); if (elapsed >= MAX_DURATION_MS && mediaRecorderRef.current?.state === 'recording') mediaRecorderRef.current.stop(); }, 200); } catch (error) { cleanupStream(); cleanupTimer(); setError(error instanceof DOMException && error.name === 'NotAllowedError' ? 'Permissão de microfone negada' : 'Erro ao acessar microfone'); setState('idle'); } }, [clear, cleanupStream, cleanupTimer, mediaRecorderRef, streamRef, chunksRef, timerRef, startTimeRef, setAudioBlob, setDurationMs, setError, setState]);
  const stopRecording = useCallback(() => { if (mediaRecorderRef.current?.state === 'recording') mediaRecorderRef.current.stop(); }, [mediaRecorderRef]);
  const playPreview = useCallback(() => { if (!audioBlob) return; stopPreview(); const url = URL.createObjectURL(audioBlob); const audio = new Audio(url); audioElementRef.current = audio; audio.onended = () => { URL.revokeObjectURL(url); audioElementRef.current = null; }; audio.play().catch(() => { URL.revokeObjectURL(url); audioElementRef.current = null; }); }, [audioBlob, stopPreview, audioElementRef]);
  return { startRecording, stopRecording, playPreview };
}
