type Player = 'player1' | 'player2';
type SetBase = { p1Games: number; p2Games: number; winner: Player | null };
type CellKind = 'winner' | 'loser' | 'neutral';

interface SetsSummaryProps { title: string; sets: SetBase[]; playerNames: { p1: string; p2: string }; startIndex?: number; }
interface EditableSet extends SetBase { index: number; isPartial: boolean; }
interface EditableSetsSummaryProps extends Omit<SetsSummaryProps, 'sets'> { sets: EditableSet[]; onEditSet: (index: number, p1Games: number, p2Games: number) => void; onRemoveSet: (index: number) => void; validationErrors?: Record<number, string>; }

function cellClass(winner: Player | null, player: Player, editable: boolean): string { const kind: CellKind = winner === player ? 'winner' : winner ? 'loser' : 'neutral'; if (kind === 'winner') return 'bg-purple-700 text-white font-bold'; if (kind === 'loser') return 'bg-gray-100 dark:bg-gray-700 text-gray-800 dark:text-gray-200'; return editable ? 'bg-gray-700 border border-white/10 text-white' : 'text-gray-300'; }
function winnerLabel(winner: Player | null, names: { p1: string; p2: string }) { return winner === 'player1' ? names.p1 : winner === 'player2' ? names.p2 : 'Em andamento'; }

export function SetsSummary({ title, sets, playerNames, startIndex = 0 }: SetsSummaryProps) { if (!sets.length) return null; return <SummaryShell title={title}>{sets.map((set, index) => <SetRow key={index} set={set} index={startIndex + index} playerNames={playerNames} />)}</SummaryShell>; }
function SetRow({ set, index, playerNames }: { set: SetBase; index: number; playerNames: { p1: string; p2: string } }) { return <div className="flex items-center gap-3 text-sm"><span className="text-gray-500 w-14 font-medium text-xs">Set {index + 1}</span><span className={`font-mono font-semibold px-2 py-1 rounded ${cellClass(set.winner, 'player1', false)}`}>{set.p1Games}</span><span className="text-gray-400">×</span><span className={`font-mono font-semibold px-2 py-1 rounded ${cellClass(set.winner, 'player2', false)}`}>{set.p2Games}</span><span className="text-xs font-semibold text-gray-500">{winnerLabel(set.winner, playerNames)}</span></div>; }

export function EditableSetsSummary({ title, sets, playerNames, startIndex = 0, onEditSet, onRemoveSet, validationErrors }: EditableSetsSummaryProps) { if (!sets.length) return null; return <SummaryShell title={title}>{sets.map((set, index) => <EditableSetRow key={set.index} set={set} index={startIndex + index} playerNames={playerNames} canRemove={sets.length > 1} onEditSet={onEditSet} onRemoveSet={onRemoveSet} validationError={validationErrors?.[set.index]} />)}</SummaryShell>; }
function EditableSetRow({ set, index, playerNames, canRemove, onEditSet, onRemoveSet, validationError }: { set: EditableSet; index: number; playerNames: { p1: string; p2: string }; canRemove: boolean; onEditSet: EditableSetsSummaryProps['onEditSet']; onRemoveSet: EditableSetsSummaryProps['onRemoveSet']; validationError?: string }) { const hasError = Boolean(validationError); const errorInputClass = hasError ? 'ring-2 ring-red-500 border-red-500' : ''; return <div className="flex items-center gap-3 text-sm"><span className="text-gray-500 w-14 font-medium text-xs">Set {index + 1}</span><div className="flex flex-col"><input type="number" value={set.p1Games} onChange={(e) => onEditSet(set.index, parseInt(e.target.value, 10) || 0, set.p2Games)} className={`w-16 text-center rounded-lg px-2 py-1 text-sm font-mono focus:outline-none focus:ring-2 focus:ring-blue-500 ${cellClass(set.winner, 'player1', true)} ${errorInputClass}`} /></div><span className="text-gray-400">×</span><div className="flex flex-col"><input type="number" value={set.p2Games} onChange={(e) => onEditSet(set.index, set.p1Games, parseInt(e.target.value, 10) || 0)} className={`w-16 text-center rounded-lg px-2 py-1 text-sm font-mono focus:outline-none focus:ring-2 focus:ring-blue-500 ${cellClass(set.winner, 'player2', true)} ${errorInputClass}`} /></div><span className="text-xs font-semibold min-w-[80px] text-gray-500">{winnerLabel(set.winner, playerNames)}</span>{hasError && <span className="text-xs text-red-400 ml-1" title={validationError}>!</span>}{canRemove && <button type="button" onClick={() => onRemoveSet(set.index)} className="text-red-500 hover:text-red-700 text-xs ml-2" title="Remover set">✕</button>}</div>; }
function SummaryShell({ title, children }: { title: string; children: React.ReactNode }) { return <div className="space-y-2"><p className="text-xs font-semibold text-gray-500 uppercase tracking-wide">{title}</p><div className="space-y-1.5 rounded-lg border border-white/5 bg-gray-700/50 px-3 py-2">{children}</div></div>; }
