import { isSetCompleted } from '@/app/match/[id]/scoring/scoringHelpers';
import type { NormalizedScoreState } from '@/core/scoring/score-normalizer';
import type { TennisFormat } from '@/lib/matchConfig';

type ScoreSet = NormalizedScoreState['sets'][number];
type Player = 'player1' | 'player2';
type Style = (set: ScoreSet | undefined, index: number, player: Player, current: boolean) => string;

export function ScoreboardHeader({ sets, numSets, currentSetIndex, tennisFormat }: { sets: ScoreSet[]; numSets: number; currentSetIndex: number; tennisFormat?: TennisFormat }) { return <thead><tr className="text-[10px] text-gray-500 dark:text-gray-400 font-mono"><th scope="col" aria-label="Jogador" className="text-left py-1 pr-2 w-[80px] sm:w-[100px]"></th>{Array.from({ length: numSets }).map((_, i) => { const set = sets[i]; const complete = set && isSetCompleted({ ...set, isTiebreak: set.isTiebreak ?? false }, tennisFormat); return <th key={i} scope="col" aria-label={`Set ${i + 1}`} className={`text-center px-1 py-1 w-7 sm:w-9 ${i === currentSetIndex ? 'font-bold text-green-600 dark:text-green-400' : ''}`}>{i === currentSetIndex ? 'atual' : complete ? i + 1 : ''}</th>; })}<th scope="col" aria-label="Pontuação final" className="text-right px-2 py-1 w-[28px] sm:w-[32px]"></th></tr></thead>; }

export function ScoreboardPlayerRow({ player, playerKey, sets, numSets, currentSetIndex, isSuspended, style }: { player: { name: string }; playerKey: Player; sets: ScoreSet[]; numSets: number; currentSetIndex: number; isSuspended?: boolean; style: Style }) { return <tr className="text-xs"><td className={`text-left py-2 pr-2 font-semibold ${isSuspended ? 'text-amber-900 dark:text-amber-200' : 'text-gray-900 dark:text-gray-100'}`}>{player.name}</td>{Array.from({ length: numSets }).map((_, i) => { const set = sets[i]; const score = set ? set.isTiebreak && set.tiebreakScore ? set.tiebreakScore[playerKey] : set[playerKey] : '-'; return <td key={i} className={`text-center px-1 py-2 text-sm font-mono rounded-sm ${style(set, i, playerKey, i === currentSetIndex)}`}>{score}</td>; })}<td className="text-right px-2 py-2" aria-label="Espaço reservado"></td></tr>; }

export function ScoreboardSummary({ sets, numSets, currentSetIndex, tennisFormat, getSetsWon }: { sets: ScoreSet[]; numSets: number; currentSetIndex: number; tennisFormat?: TennisFormat; getSetsWon: (player: Player) => number }) { return <tfoot><tr className="text-[9px] border-t border-gray-200 dark:border-gray-700"><td className="text-left py-2 pr-2 text-gray-400 dark:text-gray-500">Sets</td>{Array.from({ length: numSets }).map((_, i) => { const set = sets[i]; const complete = set && isSetCompleted({ ...set, isTiebreak: set.isTiebreak ?? false }, tennisFormat); const p1Won = set && set.player1 > set.player2; return <td key={i} className="text-center px-1 py-2">{i === currentSetIndex ? <span className="text-gray-300 dark:text-gray-600">-</span> : complete ? <span className={p1Won ? 'text-sky-600 dark:text-sky-400 font-bold' : 'text-emerald-600 dark:text-emerald-400 font-bold'}>✓</span> : <span className="text-gray-200 dark:text-gray-700">-</span>}</td>; })}<td className="text-right px-2 py-2 text-gray-400 font-mono text-[10px]">{getSetsWon('player1')}-{getSetsWon('player2')}</td></tr></tfoot>; }
